import os,sys,string
import project_cfg

ROOT_DIR = os.path.normpath(os.getcwd())

sys.path = sys.path + [os.path.join(ROOT_DIR, 'tools')]
from building import *

env = Environment(tools = ['default'],
    AS   = project_cfg.AS, ASFLAGS = project_cfg.AFLAGS,
    CC   = project_cfg.CC, CCFLAGS = project_cfg.CFLAGS,
    CXX  = project_cfg.CXX, CXXFLAGS = project_cfg.CXXFLAGS,
    AR   = project_cfg.AR, ARFLAGS = '-rc',
    LINK = project_cfg.LINK, LINKFLAGS = project_cfg.LFLAGS)

Export('ROOT_DIR')
Export('project_cfg')

objs = PrepareBuilding(env, ROOT_DIR)

TARGET='aaa'

DoBuilding(TARGET, objs)



