import os
Import('ROOT_DIR')

cwd = str(Dir('#'))
objs = []
#list = os.listdir(cwd)
list = ['app']
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(path, 'SConscript'))

Return('objs')
